[package]
name = "script-exec"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
env_logger = "0.10"
crossterm = "0.29.0"

[dev-dependencies]
insta-cmd = "0.6.0"